### ISSUE TITLE
Dapr Actor support?

### ISSUE THREAD

**Issue by AlseinX** [dapr/rust-sdk#36]
Will it be supported?

**Comment by yaron2** [comment]
We want to support Rust actors, but currently this is not on the roadmap for maintainers. Community contributions are welcome though.

**Comment by thomas-tribus** [comment]
Not a complete implementation by a (very very) long shot, but I made a WIP PR to gather some feedback on a general solution direction: https://github.com/dapr/rust-sdk/pull/63.

First ever open source contribution and fairly new to rust, so really open for any feedback. Hope this helps somebody.

**Comment by hansmbakker** [comment]
@thomas-tribus cool that you worked on this!

Would it be an idea to split into 2 parts?
- invoking an actor (client)
- hosting / implementing an actor (server)

This might make it easier to merge already a part of your work - I guess the client part might be less complex than the server part.

**Comment by thomas-tribus** [comment]
@hansmbakker Thanks for your reply.  I also replied in the PR (#63 )

Exposing the client (invoke actor) would require the using HTTP API, because for some reason the GRPC API doesn't seem to include actors. So that drags in a bit of work on that as well. 

Having an idiomatic actor client implementation is a lot of work, that might actually be beyond my rust skills. It would require something like reflection I think, to have some parity with the C# implementation. 

The server might actually be easier, at least for the case where you don't serve other dapr APIs. 

But either way, I won't have much time for this at the moment unfortunately.

**Comment by mikeee** [comment]
Addressed by #99
